stages:
 - transform
 - build
 - deploy

 build:
  stage: build
  script:
    - ls -l
    - npm install
    - npm run build
  artifacts:
    paths:
      - $DEPLOY_SRC
  only:
    refs:
      - master
      - staging

include:
  - project: 'ttc/gitlab-ci-templates'
    file: 'ttc-json-data-transform-tpl.yml'

  - project: 'ttc/gitlab-ci-templates'
    file: 'ttc-json-data-deploy-tpl.yml'
